version: '3'

networks:
  timeline-back:
    driver: bridge

services:
  timeline-mysql:
    container_name: timeline-mysql
    image: mysql:${TIMELINE_MYSQL_VERSION}
    networks:
      - timeline-back
    expose:
      - '${TIMELINE_MYSQL_PORT}'
    environment:
      - MYSQL_ROOT_PASSWORD=${TIMELINE_MYSQL_PASSWORD}

  timeline-graphql:
    container_name: timeline-graphql
    image: k0rdan/timeline-graphql:${TIMELINE_GRAPHQL_VERSION}
    networks:
      - timeline-back
    ports:
      - '${TIMELINE_GRAPHQL_PORT}:${TIMELINE_GRAPHQL_PORT}'
    environment:
      GRAPHQL_CONFIG_ENDPOINT_NAME: ${ENV}
      PRISMA_MANAGEMENT_API_SECRET: ${TIMELINE_PRISMA_MANAGEMENTAPISECRET}
    command: ['bash', '-c', 'cd /usr/timeline-graphql/prisma', 'prisma deploy']

  timeline-prisma:
    container_name: timeline-prisma
    image: k0rdan/timeline-prisma:${TIMELINE_PRISMA_VERSION}
    networks:
      - timeline-back
    ports:
      - '${TIMELINE_PRISMA_PORT}:${TIMELINE_PRISMA_PORT}'
    environment:
      DEBUG: '*'
      PRISMA_CONFIG: |
        managementApiSecret: ${TIMELINE_PRISMA_MANAGEMENTAPISECRET}
        port: ${TIMELINE_PRISMA_PORT}
        databases:
          default:
            connector: mysql
            migrations: true
            host: timeline-mysql
            port: ${TIMELINE_MYSQL_PORT}
            user: ${TIMELINE_MYSQL_USER}
            password: ${TIMELINE_MYSQL_PASSWORD}
    command:
      [
        'dockerize',
        '--wait',
        'http://localhost:${TIMELINE_PRISMA_PORT}',
        '--wait',
        'http://localhost:${TIMELINE_GRAPHQL_PORT}',
        'prisma',
        'deploy',
      ]
