version: '3'

networks:
  timeline-back:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
      com.docker.network.bridge.host_binding_ipv4: '0.0.0.0'
      com.docker.network.driver.mtu: '1350'

services:
  mysql:
    container_name: timeline-mysql
    image: mysql:latest
    networks:
      - timeline-back
    volumes:
      # Default MySQL data volume
      - /var/lib/mysql
      # Init database with our SQL file
      - ./mysql/production/:/docker-entrypoint-initdb.d/
    expose:
      # Default MySQL listening port
      - '${TIMELINE_MYSQL_PORT}'
    environment:
      # Environment variables preceed by TIMELINE_MYSQL_
      - MYSQL_ROOT_PASSWORD=${TIMELINE_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${TIMELINE_MYSQL_DATABASE}
